services:
  db:
    image: mysql:8.0
    container_name: oykus-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  backend:
    build: ./backend
    container_name: oykus-backend
    command: sh -c "flask run --host=0.0.0.0 --port=8000 --reload"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      TZ: ${TZ}
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    build: ./frontend
    container_name: oykus-frontend
    command: sh -c "npm run dev"
    depends_on:
      - db
      - backend
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      TZ: ${TZ}
      VITE_API_URL: ${VITE_API_URL}
      VITE_WATCH_USE_POLLING: ${VITE_WATCH_USE_POLLING}

volumes:
  db_data: 