services:
  db:
    image: mysql:8.0
    container_name: oykus-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  backend:
    build: ./backend
    container_name: oykus-backend
    command: sh -c "flask --app hello run --host=0.0.0.0 --port=5000 --debug"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      TZ: ${TZ}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build: ./frontend
    container_name: oykus-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      TZ: ${TZ}
      VITE_API_URL: ${VITE_API_URL}
      VITE_WATCH_USE_POLLING: ${VITE_WATCH_USE_POLLING}

  nginx:
    image: nginx:alpine
    container_name: oykus-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      TZ: ${TZ}

volumes:
  db_data: 