services:
  db:
    image: postgres:15
    container_name: oykus-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  backend:
    build: ./backend
    container_name: oykus-backend
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      TZ: ${TZ}
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    build: ./frontend
    container_name: oykus-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      TZ: ${TZ}
      VITE_API_URL: ${VITE_API_URL}
      VITE_WATCH_USE_POLLING: ${VITE_WATCH_USE_POLLING}

  nginx:
    image: nginx:alpine
    container_name: oykus-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      TZ: ${TZ}

volumes:
  db_data: 