"""empty message

Revision ID: 0d001dbf9847
Revises: 3454be655992
Create Date: 2025-08-05 21:45:12.814225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d001dbf9847'
down_revision = '3454be655992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oyk_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('abbr', sa.String(length=3), nullable=False),
    sa.Column('is_abbr_auto', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['oyk_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('oyk_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oyk_characters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oyk_characters_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oyk_characters_is_active'))
        batch_op.drop_index(batch_op.f('ix_oyk_characters_id'))

    op.drop_table('oyk_characters')
    # ### end Alembic commands ###
