"""empty message

Revision ID: 0ff07f53818d
Revises: d33004dc4ed2
Create Date: 2025-08-07 11:09:53.832280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff07f53818d'
down_revision = 'd33004dc4ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oyk_worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('abbr', sa.String(length=3), nullable=False),
    sa.Column('is_abbr_auto', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['oyk_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oyk_worlds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oyk_worlds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oyk_worlds_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_oyk_worlds_is_public'), ['is_public'], unique=False)

    op.create_table('oyk_world_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('c_primary', sa.String(length=9), nullable=True),
    sa.Column('c_primary_fg', sa.String(length=9), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['oyk_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oyk_world_themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oyk_world_themes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oyk_world_themes_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_world_themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oyk_world_themes_is_active'))
        batch_op.drop_index(batch_op.f('ix_oyk_world_themes_id'))

    op.drop_table('oyk_world_themes')
    with op.batch_alter_table('oyk_worlds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oyk_worlds_is_public'))
        batch_op.drop_index(batch_op.f('ix_oyk_worlds_is_active'))
        batch_op.drop_index(batch_op.f('ix_oyk_worlds_id'))

    op.drop_table('oyk_worlds')
    # ### end Alembic commands ###
