"""empty message

Revision ID: 18a6360c951f
Revises: b08f9c2d3bf8
Create Date: 2025-08-05 22:38:08.124732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a6360c951f'
down_revision = 'b08f9c2d3bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resistance_physical', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resistance_mental', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resistance_spiritual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attribute_strength', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attribute_constitution', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attribute_dexterity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attribute_perception', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attribute_intelligence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attribute_willpower', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_characters', schema=None) as batch_op:
        batch_op.drop_column('skills')
        batch_op.drop_column('attribute_willpower')
        batch_op.drop_column('attribute_intelligence')
        batch_op.drop_column('attribute_perception')
        batch_op.drop_column('attribute_dexterity')
        batch_op.drop_column('attribute_constitution')
        batch_op.drop_column('attribute_strength')
        batch_op.drop_column('resistance_spiritual')
        batch_op.drop_column('resistance_mental')
        batch_op.drop_column('resistance_physical')

    # ### end Alembic commands ###
