"""init_users

Revision ID: 3454be655992
Revises: 
Create Date: 2025-08-04 14:21:47.062836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3454be655992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oyk_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('playername', sa.String(length=120), nullable=False),
    sa.Column('abbr', sa.String(length=3), nullable=False),
    sa.Column('is_abbr_auto', sa.Boolean(), nullable=True),
    sa.Column('limit_worlds', sa.Integer(), nullable=True),
    sa.Column('total_worlds', sa.Integer(), nullable=True),
    sa.Column('limit_world_themes', sa.Integer(), nullable=True),
    sa.Column('total_world_themes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('oyk_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oyk_users_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_oyk_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_oyk_users_playername'), ['playername'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oyk_users_playername'))
        batch_op.drop_index(batch_op.f('ix_oyk_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_oyk_users_id'))

    op.drop_table('oyk_users')
    # ### end Alembic commands ###
