"""empty message

Revision ID: 975423e57dd2
Revises: 18a6360c951f
Create Date: 2025-08-05 23:00:42.191683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '975423e57dd2'
down_revision = '18a6360c951f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_characters', schema=None) as batch_op:
        batch_op.alter_column('resistance_physical',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               nullable=False)
        batch_op.alter_column('resistance_mental',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               nullable=False)
        batch_op.alter_column('resistance_spiritual',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               nullable=False)
        batch_op.alter_column('attribute_strength',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('attribute_constitution',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('attribute_dexterity',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('attribute_perception',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('attribute_intelligence',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('attribute_willpower',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_characters', schema=None) as batch_op:
        batch_op.alter_column('attribute_willpower',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('attribute_intelligence',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('attribute_perception',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('attribute_dexterity',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('attribute_constitution',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('attribute_strength',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('resistance_spiritual',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('resistance_mental',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('resistance_physical',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
