"""empty message

Revision ID: c8605493828e
Revises: d5c3d790892e
Create Date: 2025-08-07 12:12:14.069129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8605493828e'
down_revision = 'd5c3d790892e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oyk_task_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('colour', sa.String(length=9), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['oyk_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oyk_task_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oyk_task_status_id'), ['id'], unique=False)

    op.create_table('oyk_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['oyk_task_status.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['oyk_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oyk_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oyk_tasks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oyk_tasks_id'))

    op.drop_table('oyk_tasks')
    with op.batch_alter_table('oyk_task_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oyk_task_status_id'))

    op.drop_table('oyk_task_status')
    # ### end Alembic commands ###
