"""empty message

Revision ID: d33004dc4ed2
Revises: 975423e57dd2
Create Date: 2025-08-06 21:11:08.204596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33004dc4ed2'
down_revision = '975423e57dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('is_slug_auto', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_oyk_users_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oyk_users_slug'))
        batch_op.drop_column('is_slug_auto')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
